version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "squadbot"
      POSTGRES_USER: "squadbot"
      POSTGRES_PASSWORD: "p4ssw0rd"
    ports:
      - 5432:5432
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379