version: '3.7'
services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
      - localtunnel
    environment:
      USE_NATIVE_ENV: "true"
      DATABASE_URL: "postgres://squadbot:p4ssw0rd@postgres:5432/squadbot"
      TELEGRAM_BOT_TOKEN: "<your telegram bot token>"
      DEBUG_CHAT_ID: "-123456789"
      GOOGLE_API_CREDENTIALS: "<stringified credentials JSON file>"
      DOMAIN: "https://squadbot-staging.loca.lt"
      PORT: "1234"
    volumes:
      - .:/squadbot
    command: |
      ./wait-for-it.sh postgres:5432 -t 120 --
      npm start

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "squadbot"
      POSTGRES_USER: "squadbot"
      POSTGRES_PASSWORD: "p4ssw0rd"

  localtunnel:
    container_name: localtunnel
    image: efrecon/localtunnel
    restart: always
    command:
      --local-host backend --print-requests --port 1234 --subdomain squadbot-staging
