services:
  sb_app:
    container_name: sb_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - sb_postgres
      - sb_redis
    environment:
      PORT: "3000"
      DATABASE_URL: "postgres://squadbot:p4ssw0rd@sb_postgres:5432/squadbot"
      REDIS_URL: "redis://sb_redis:6379"
      # security
      TOKEN_SECRET: "$TOKEN_SECRET"
      CORS_ORIGIN: "$CORS_ORIGIN"
      # telegram
      TELEGRAM_BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
      WEB_APP_URL: "$WEB_APP_URL"
      WEB_APP_NAME: "$WEB_APP_NAME"
      # logging
      LOG_LEVEL: "info"
      DEBUG_CHAT_ID: "$DEBUG_CHAT_ID"
      # OCR
      OCR_SPACE_API_KEY: "$OCR_SPACE_API_KEY"
      OCR_SPACE_ENDPOINT: "$OCR_SPACE_ENDPOINT"
      # telegram (advanced)
      TELEGRAM_APP_ID: "$TELEGRAM_APP_ID"
      TELEGRAM_APP_HASH: "$TELEGRAM_APP_HASH"
      TELEGRAM_SESSION_STRING: "$TELEGRAM_SESSION_STRING"
      TELEGRAM_INSTAGRAM_INTEGRATION_BOT_ID: "$TELEGRAM_INSTAGRAM_INTEGRATION_BOT_ID"
      TELEGRAM_WHITELISTED_CHAT_IDS_FOR_INSTAGRAM_INTEGRATION: "$TELEGRAM_WHITELISTED_CHAT_IDS_FOR_INSTAGRAM_INTEGRATION"
    volumes:
      - "./files:/app/files"
    networks:
      - "global_network"

  sb_postgres:
    container_name: sb_postgres
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "squadbot"
      POSTGRES_USER: "squadbot"
      POSTGRES_PASSWORD: "p4ssw0rd"
    volumes:
      - "./local/postgres-data:/var/lib/postgresql/data"
    networks:
      - "global_network"

  sb_redis:
    container_name: sb_redis
    restart: unless-stopped
    image: redis
    networks:
      - "global_network"

networks:
  global_network:
    external: true
